Repository webpack-contrib/mini-css-extract-plugin, pull requests merged in 2018-08, with the labels that each got.

#231 docs(readme): move long term caching guide from errant section
  README.md
Labels: pr_action: Review, semver: Patch, status: Approved, type: Documentation

#227 build(babel): use same node version as declared in package.json
  .babelrc
Labels: semver: Patch, status: Approved, type: Build

#247 chore(package): add a description
  package.json
Labels: semver: Patch, status: Approved, type: Chore
