Repository webpack-contrib/mini-css-extract-plugin, pull requests merged in 2018-09, with the labels that each got.

#258 test: fix `jest` config and rename files
  jest.config.js
  package-lock.json
  src/index.js
  src/loader.js
  test/cases/composes-async/expected/2.css
  test/cases/js-hash/expected/style.3ffccb34a605ebf39f4d.js
Labels: semver: patch, status: approved, type: test

#265 refactor: rename `NS` to `MODULE_TYPE` and use a static value
  src/index.js
  src/loader.js
Labels: pr: review, priority: 4 (nice to have), semver: patch, severity: 4 (inconvenient), status: pending, type: refactor

#177 fix(loader): pass `emitFile` to the child compilation (`loaderContext.emitFile`)
  src/index.js
  src/loader.js
  test/TestMemoryFS.test.js
Labels: semver: patch, status: approved, type: bug

#269 docs(readme): add `media-query-splitting-plugin` (Media Query Plugin)
  README.md
Labels: pr: review, semver: patch, status: pending, type: docs
