Repository webpack-contrib/mini-css-extract-plugin, pull requests merged in 2018-06, with the labels that each got.

#127 Do not match .ass
  README.md
Labels: semver: Patch, type: Documentation

#187 Update README.md
  README.md
  package.json
  test/cases/simple-publicpath/expected/main.css
  test/cases/simple-publicpath/index.js
  test/cases/simple-publicpath/react.svg
  test/cases/simple-publicpath/style.css
  test/cases/simple-publicpath/webpack.config.js
Labels: type: Documentation

#130 Fix CSS ordering for config with multiple entry points
  src/index.js
  test/cases/multiple-entry/a.css
  test/cases/multiple-entry/async-one.js
  test/cases/multiple-entry/async-two.js
  test/cases/multiple-entry/b.css
  test/cases/multiple-entry/c.css
  test/cases/multiple-entry/d.css
  test/cases/multiple-entry/expected/async-one.css
  test/cases/multiple-entry/expected/async-two.css
  test/cases/multiple-entry/expected/main-one.css
  test/cases/multiple-entry/expected/main-two.css
  test/cases/multiple-entry/index-one.js
  test/cases/multiple-entry/index-two.js
  test/cases/multiple-entry/webpack.config.js
Labels: pr_action: Review, semver: Patch, type: Bug
